### ISSUE TITLE
Closing the GUI does not seem to terminate the flatpak process

### ISSUE THREAD

**Issue by Mershl** [flathub/org.gnome.Boxes#69] opened 2021-11-16 15:04 UTC
## Description
Closing the GUI does not seem to terminate the flatpak process allowing for parallel processes and potential zombie processes of Boxes.

## Reproducer
1) `flatpak run org.gnome.Boxes`
2) `flatpak ps | grep .Boxes`
```
Instance   PID   Application                          Runtime
2999822485	44717	org.gnome.Boxes	org.gnome.Platform
```
3) Close the GUI using mouse or keyboard
4) `flatpak ps | grep .Boxes`
```
Instance   PID   Application                          Runtime
2999822485	44717	org.gnome.Boxes	org.gnome.Platform
```
5) `flatpak run org.gnome.Boxes`
6) Do NOT close the GUI this time
7) Execute from a separate shell: `flatpak ps | grep .Boxes`
```
Instance   PID   Application                          Runtime
120344436  45630 org.gnome.Boxes                      org.gnome.Platform
2999822485 44717 org.gnome.Boxes                      org.gnome.Platform
```

## Tested on
Gnome 41.1 (Fedora 35)
flatpak 1.12.2

**Comment by losuler** [comment] 2023-05-13 18:22
I thought Boxes wasn't launching but I realised it was this issue that's still happening. Reproduced the same way as with @Mershl. Was only able to solve it by running:

```
flatpak kill org.gnome.Boxes
```

Here's the logs from starting Boxes (after killing it) by running `flatpak run -v org.gnome.Boxes` and then closing it:

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /var/home/user/.local/share/flatpak
F: Opening user flatpak installation at path /var/home/user/.local/share/flatpak
F: Opening user flatpak installation at path /var/home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/3c158bcbcb8af8163373817cbabeac27a78a2e8876bcf9204209062b5f96daba/files/lib32 does not exist
F: Allocated instance id 3638664951
F: Add defaults in dir /org/gnome/Boxes/
F: Add locks in dir /org/gnome/Boxes/
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/var/home/user/.config/pulse/client.conf': Error opening file /var/home/user/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 gnome-boxes'

(gnome-boxes:2): GLib-GObject-CRITICAL **: 04:15:23.220: ../gobject/gsignal.c:2728: handler '2965' of instance '0x5649929f0530' is not blocked
```

GNOME 43.4 (Fedora 37 Silverblue)
Flatpak 1.14.4

**Comment by losuler** [comment] 2023-05-13 18:29
Strangely after closing Boxes, `flatpak run -v org.gnome.Boxes` appears to still open it (previously this command wasn't). However, it still won't open from the GNOME app launcher.

**Comment by sidt4** [comment] 2023-12-23 08:30
Is this still reproducible ?

I cannot reproduce it on `Debian unstable` with `flatpak-1.15.6`. Maybe this is a Fedora specific issue ?

**Comment by artificialsimon** [comment] 2024-05-06 16:32
Same problem here
`$ flatpak run -v org.gnome.Boxes                                                                                                                                                           (base) 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/simon/.local/share/flatpak
F: Opening user flatpak installation at path /home/simon/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/org.gnome.Boxes/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/simon/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/46/2554ce6b3f3ee0866a15ecc0533d3c2c5735064e8218d523b88c637bbea206cf/files/lib32 does not exist
F: Allocated instance id 743253967
F: Add defaults in dir /org/gnome/Boxes/
F: Add locks in dir /org/gnome/Boxes/
F: Allowing host-fs access
F: skipping export for path /usr/libx32
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/simon/.config/pulse/client.conf': Error opening file /home/simon/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=43'
F: Running 'bwrap --args 40 gnome-boxes'
Gtk-Message: 17:28:37.050: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:28:37.051: Failed to load module "canberra-gtk-module"

(org.gnome.Boxes:2): GLib-GObject-CRITICAL **: 17:28:38.567: ../gobject/gsignal.c:2635: handler '3115' of instance '0x6338e1b0b280' is not blocked
`
After clossing it from the GUI:
`$ flatpak ps                                                                                                                                                                               (base) 
Instance   PID     Application     Runtime
1874276684 1417119 org.gnome.Boxes org.gnome.Platform
`
`$ ps -fea | grep boxes                                                                                                                                                                                                                                  (base) 
simon    1417131    2678  0 17:30 pts/0    00:00:00 bwrap --args 40 gnome-boxes
`
If I kill the process with kill or flatpak kill then I can restart Boxes.
Ubuntu 22.04
`uname -a                                                                                                                                                                                 (base) 
Linux napier-hp 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
Flatpack 1.12.7

Thanks

**Comment by A6GibKm** [comment] 2024-05-07 12:45
Please report upstream, this is only for issues specific to the flatpak distribution of the app and this is not one.

**Closed** 2024-05-17 10:33 UTC
